package com.vyay.core.entity.balance;

import com.vyay.core.entity.User;
import com.vyay.core.entity.group.Group;
import com.vyay.core.entity.reference.Currency;
import com.vyay.core.enums.LedgerSourceType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcType;
import org.hibernate.dialect.PostgreSQLEnumJdbcType;
import org.springframework.data.domain.Persistable;

import java.time.Instant;
import java.util.UUID;

/**
 * Append-only, HMAC-signed ledger. Deliberately NOT on the base hierarchy:
 * the id is HAND-ASSIGNED before signing and is part of the signed payload, so
 * it must never be (re)generated by an inherited @PrePersist.
 *
 * Spring Data normally treats a non-null @Id as an existing entity and calls
 * EntityManager.merge(), which results in an unnecessary SELECT before the
 * INSERT. Ledger entries are immutable and append-only, so every instance that
 * reaches save() is guaranteed to be new. Implementing Persistable forces
 * persist() instead of merge(), avoiding that extra round-trip.
 */
@Entity
@Table(name = "balance_ledger")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class BalanceLedgerEntry implements Persistable<UUID> {

    @Id
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "group_id", nullable = false, updatable = false)
    private Group group;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false, updatable = false)
    private User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "currency_code", nullable = false, updatable = false)
    private Currency currency;

    @Column(name = "delta_minor", nullable = false, updatable = false)
    private Long deltaMinor;

    @Enumerated(EnumType.STRING)
    @JdbcType(PostgreSQLEnumJdbcType.class)
    @Column(name = "source_type", columnDefinition = "ledger_source_type", nullable = false, updatable = false)
    private LedgerSourceType sourceType;

    @Column(name = "source_id", nullable = false, updatable = false)
    private UUID sourceId;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "hmac", nullable = false, updatable = false, length = 64)
    private String hmac;

    /**
     * Ledger entries are append-only. Every instance passed to save() is a
     * brand-new event and should always be persisted, never merged.
     */
    @Override
    @Transient
    public boolean isNew() {
        return true;
    }
}